Repository DEFRA/rod-licensing, pull requests merged in 2020-08, with the labels that each got.

#273 Add additional logging to track OAuth token refresh behaviour
  docker/env/sales_api.env
  packages/dynamics-lib/package.json
  packages/dynamics-lib/src/__mocks__/adal-node.js
  packages/dynamics-lib/src/client/__tests__/dynamics-client.spec.js
  packages/dynamics-lib/src/client/dynamics-client.js
  packages/sales-api-service/src/server/index.js
Labels: enhancement

#276 Workaround for bug in adal-node failing to cache tokens and leaking memory
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/dynamics-lib/src/client/dynamics-client.js
Labels: bug

#277 Update sales-api to correctly set keep-alive timeout on the server listener
  packages/sales-api-service/README.md
  packages/sales-api-service/src/config.js
  packages/sales-api-service/src/server/__tests__/index.spec.js
  packages/sales-api-service/src/server/index.js
Labels: enhancement

#284 Remove adal-node and replace with simple-oauth2
  docker/env/fulfilment_job.secrets.env
  docker/env/sales_api.secrets.env
  package-lock.json
  package.json
  packages/dynamics-lib/README.md
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/dynamics-lib/src/__mocks__/adal-node.js
  packages/dynamics-lib/src/__mocks__/simple-oauth2-mock-helper.js
  packages/dynamics-lib/src/__mocks__/simple-oauth2.js
  packages/dynamics-lib/src/client/__tests__/dynamics-client.spec.js
  packages/dynamics-lib/src/client/dynamics-client.js
  packages/fulfilment-job/src/__mocks__/adal-node.js
  packages/fulfilment-job/src/__mocks__/simple-oauth2.js
  packages/sales-api-service/src/__mocks__/adal-node.js
  packages/sales-api-service/src/__mocks__/simple-oauth2.js
  packages/sales-api-service/src/server/plugins/health.js
Labels: enhancement

#286 Add validation to the Sales API config and convert types as required
  packages/sales-api-service/src/__tests__/config.spec.js
  packages/sales-api-service/src/config.js
Labels: enhancement

#263 Prevent expletives from being generated in the licence number
  packages/business-rules-lib/src/validators/permission.js
  packages/sales-api-service/src/services/permissions.service.js
Labels: enhancement

#287 Workaround for prettier-standard issues indenting ternary expressions
  package.json
Labels: bug

#295 Expose concession id in renewals authentication response
  packages/dynamics-lib/src/entities/__tests__/concession-proof.entity.spec.js
  packages/dynamics-lib/src/entities/concession-proof.entity.js
  packages/dynamics-lib/src/queries/__tests__/fulfilment.queries.spec.js
  packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
  packages/dynamics-lib/src/queries/__tests__/predefined-query.spec.js
  packages/dynamics-lib/src/queries/permission.queries.js
  packages/dynamics-lib/src/queries/predefined-query.js
  packages/gafl-webapp-service/src/pages/renewals/identify/__mocks__/data/authentication-result.js
  packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/sales-api-service/src/server/routes/__tests__/authenticate.spec.js
  packages/sales-api-service/src/server/routes/authenticate.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#302 Rework services to allow issue and expiry to be calculated after payment
  package.json
  packages/connectors-lib/src/__mocks__/aws-mock-helper.js
  packages/connectors-lib/src/__tests__/document-client-decorator.spec.js
  packages/connectors-lib/src/__tests__/govuk-pay-api.spec.js
  packages/connectors-lib/src/documentclient-decorator.js
  packages/connectors-lib/src/govuk-pay-api.js
  packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
  packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
  packages/gafl-webapp-service/src/processors/__tests__/api-transaction.spec.js
  packages/gafl-webapp-service/src/processors/__tests__/date-and-time-display.spec.js
  packages/gafl-webapp-service/src/processors/api-transaction.js
  packages/gafl-webapp-service/src/processors/date-and-time-display.js
  packages/payment-mop-up-job/README.md
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/payment-mop-up-job/src/__test__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/constants.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/payment-mop-up-job/src/processors/__test__/processor.spec.js
  packages/payment-mop-up-job/src/processors/processor.js
  packages/pocl-job/src/io/__tests__/db.spec.js
  packages/pocl-job/src/io/db.js
  packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/sales-api-service/src/__mocks__/test-data.js
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/authenticate.schema.js
  packages/sales-api-service/src/schema/option-set.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/services/paymentjournals/__tests__/payment-journals.service.spec.js
  packages/sales-api-service/src/services/paymentjournals/payment-journals.service.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/constants.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
Labels: enhancement

#304 Add constant for no. of minutes after payment and fix start date calculation
  packages/business-rules-lib/src/constants.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
Labels: enhancement

#307 Fix handling of date/times when running in docker container
  packages/business-rules-lib/src/constants.js
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/processors/__tests__/date-and-time-display.spec.js
  packages/gafl-webapp-service/src/processors/api-transaction.js
  packages/gafl-webapp-service/src/processors/date-and-time-display.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/pocl-job/src/__mocks__/test-2-records.xml
  packages/pocl-job/src/transform/bindings/pocl/transaction/transaction.bindings.js
Labels: bug

#309 Correct use of moment-timezone for POCL record start-time
  packages/pocl-job/src/transform/bindings/pocl/transaction/transaction.bindings.js
Labels: bug

#310 Add pricing tables to the licence selection pages
  packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
  packages/gafl-webapp-service/src/__mocks__/data/permits.js
  packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
  packages/gafl-webapp-service/src/__mocks__/test-utils-system.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/route.js
  packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk
  packages/gafl-webapp-service/src/pages/macros/standard-form.njk
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/order-complete/route.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/processors/__tests__/confirmation-pdf.spec.js
  packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
  packages/gafl-webapp-service/src/processors/concession-helper.js
  packages/gafl-webapp-service/src/processors/confirmation-pdf.js
  packages/gafl-webapp-service/src/processors/filter-permits.js
  packages/gafl-webapp-service/src/processors/licence-type-display.js
  packages/gafl-webapp-service/src/processors/pricing-summary.js
  packages/gafl-webapp-service/src/session-cache/__tests__/cache-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#312 OpenID Connect authentication and role based authorisation for telesales
  docker/env/gafl_webapp_telesales.secrets.env
  packages/connectors-lib/src/sales-api-connector.js
  packages/dynamics-lib/src/__mocks__/TestEntity.js
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/__tests__/role.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/system-user-role.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/system-user.entity.spec.js
  packages/dynamics-lib/src/entities/role.entity.js
  packages/dynamics-lib/src/entities/system-user-role.entity.js
  packages/dynamics-lib/src/entities/system-user.entity.js
  packages/dynamics-lib/src/index.js
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/__mocks__/openid-client.js
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/__tests__/server.telesales.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/oidc-handler.spec.js
  packages/gafl-webapp-service/src/handlers/oidc-handler.js
  packages/gafl-webapp-service/src/pages/errors/server-error.njk
  packages/gafl-webapp-service/src/pages/guidance/cookies.njk
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/pages/oidc/account-disabled.njk
  packages/gafl-webapp-service/src/pages/oidc/role-required.njk
  packages/gafl-webapp-service/src/plugins.js
  packages/gafl-webapp-service/src/routes/__tests__/telesales-routes.spec.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/routes/routes.js
  packages/gafl-webapp-service/src/routes/static-routes.js
  packages/gafl-webapp-service/src/routes/telesales-routes.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
  packages/gafl-webapp-service/src/uri.js
  packages/sales-api-service/src/schema/system-user.schema.js
  packages/sales-api-service/src/server/routes/__tests__/system-users.spec.js
  packages/sales-api-service/src/server/routes/index.js
  packages/sales-api-service/src/server/routes/system-users.js
  packages/sales-api-service/src/services/reference-data.service.js
Labels: enhancement

#315 Bump package dependencies
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#317 Security headers
  packages/gafl-webapp-service/src/plugins.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
Labels: enhancement

#318 Improve logging output when encountering errors persisting to Dynamics
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/base.entity.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
  packages/pocl-job/src/staging/create-transactions.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/sales-api-service/src/sales-api-service.js
  packages/sales-api-service/src/server/__tests__/server.spec.js
  packages/sales-api-service/src/server/plugins/__tests__/health.spec.js
  packages/sales-api-service/src/server/plugins/__tests__/swagger.spec.js
  packages/sales-api-service/src/server/routes/__tests__/authenticate.spec.js
  packages/sales-api-service/src/server/routes/__tests__/option-sets.spec.js
  packages/sales-api-service/src/server/routes/__tests__/payment-journals.spec.js
  packages/sales-api-service/src/server/routes/__tests__/reference-data.spec.js
  packages/sales-api-service/src/server/routes/__tests__/staging-exceptions.spec.js
  packages/sales-api-service/src/server/routes/__tests__/system-users.spec.js
  packages/sales-api-service/src/server/routes/__tests__/transaction-files.spec.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/server/server.js
Labels: enhancement

#325 Fix OIDC handler to handle accounts not present in Dynamics
  packages/gafl-webapp-service/src/handlers/__tests__/oidc-handler.spec.js
  packages/gafl-webapp-service/src/handlers/oidc-handler.js
  packages/gafl-webapp-service/src/pages/oidc/account-disabled.njk
Labels: bug
