Repository DEFRA/rod-licensing, pull requests merged in 2020-05, with the labels that each got.

#127 Update travis to only ignore release chores and bump all dependencies
  .travis.yml
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/entities/base.entity.js
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/lib/session-manager.js
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#128 Update Sales API to relect latest changes to Dynamics schema
  packages/dynamics-lib/src/__mocks__/option-set-data.json
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/__tests__/concession-proof.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/contact.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/fulfilment-request-file.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/fulfilment-request.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/permit.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/pocl-file.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/transaction-journal.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/transaction.entity.spec.js
  packages/dynamics-lib/src/entities/permit.entity.js
  packages/dynamics-lib/src/entities/recurring-payment.entity.js
  packages/dynamics-lib/src/entities/transaction.entity.js
  packages/sales-api-service/src/__mocks__/test-data.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
  packages/sales-api-service/src/services/permissions.service.js
  packages/sales-api-service/src/services/reference-data.service.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#129 Add guidance for building and running docker services locally
  README.md
  docker/README.md
  docker/services.build.yml
Labels: documentation

#152 Add FTP/S3 support to POCL and SFTP server to docker development infrastructure
  .gitignore
  docker/README.md
  docker/infrastructure.yml
  docker/resources/infrastructure/elasticmq/elasticmq.conf
  docker/resources/infrastructure/localstack/localstack-cfn.yml
  docker/resources/infrastructure/localstack/localstack-init.sh
  docker/resources/infrastructure/sftp/ssh_host_ed25519_key
  docker/resources/infrastructure/sftp/ssh_host_ed25519_key.pub
  docker/resources/infrastructure/sftp/ssh_host_rsa_key
  docker/resources/infrastructure/sftp/ssh_host_rsa_key.pub
  docker/resources/infrastructure/sftp/sshd_config
  docker/volumes/sftp/fulfilment/README.md
  docker/volumes/sftp/pocl/README.md
  package-lock.json
  packages/connectors-lib/README.md
  packages/connectors-lib/src/__mocks__/aws-mock-helper.js
  packages/connectors-lib/src/__tests__/aws.spec.js
  packages/connectors-lib/src/aws.js
  packages/connectors-lib/src/config.js
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/pocl-job/src/__mocks__/ssh2-sftp-client.js
  packages/pocl-job/src/__tests__/pocl-job.spec.js
  packages/pocl-job/src/__tests__/pocl-processor.spec.js
  packages/pocl-job/src/io/__tests__/db.spec.js
  packages/pocl-job/src/io/__tests__/file.spec.js
  packages/pocl-job/src/io/db.js
  packages/pocl-job/src/io/file.js
  packages/pocl-job/src/pocl-job.js
  packages/pocl-job/src/pocl-processor.js
  packages/pocl-job/src/staging/__tests__/create-transactions.spec.js
  packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
  packages/pocl-job/src/staging/__tests__/pocl-data-staging.spec.js
  packages/pocl-job/src/staging/constants.js
  packages/pocl-job/src/staging/create-transactions.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/pocl-job/src/staging/pocl-data-staging.js
  packages/pocl-job/src/transport/__tests__/ftp-to-s3.spec.js
  packages/pocl-job/src/transport/__tests__/s3-to-local.spec.js
  packages/pocl-job/src/transport/constants.js
  packages/pocl-job/src/transport/ftp-to-s3.js
  packages/pocl-job/src/transport/s3-to-local.js
Labels: enhancement

#154 Add explicit frontend dependency for semver otherwise it isn't installed in production but required by @hapi/scooter
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
Labels: bug

#155 Add functionality to populate Dynamics POCL file entity with import details
  .gitignore
  docker/infrastructure.yml
  package.json
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/sales-api-connector.js
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/__tests__/base.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/transaction.entity.spec.js
  packages/dynamics-lib/src/entities/base.entity.js
  packages/dynamics-lib/src/entities/permission.entity.js
  packages/dynamics-lib/src/entities/pocl-file.entity.js
  packages/dynamics-lib/src/entities/transaction.entity.js
  packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
  packages/pocl-job/README.md
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/pocl-job/src/io/__tests__/file.spec.js
  packages/pocl-job/src/io/db.js
  packages/pocl-job/src/io/file.js
  packages/pocl-job/src/pocl-processor.js
  packages/pocl-job/src/staging/__tests__/pocl-data-staging.spec.js
  packages/pocl-job/src/staging/constants.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/pocl-job/src/staging/pocl-data-staging.js
  packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/transaction.bindings.spec.js
  packages/pocl-job/src/transform/bindings/pocl/transaction/transaction.bindings.js
  packages/pocl-job/src/transport/__tests__/ftp-to-s3.spec.js
  packages/pocl-job/src/transport/__tests__/s3-to-local.spec.js
  packages/pocl-job/src/transport/ftp-to-s3.js
  packages/pocl-job/src/transport/s3-to-local.js
  packages/sales-api-service/README.md
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/concession-proof.schema.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/transaction-file.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
  packages/sales-api-service/src/schema/validators/validators.js
  packages/sales-api-service/src/server/routes/__tests__/transaction-files.spec.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/server/routes/index.js
  packages/sales-api-service/src/server/routes/transaction-files.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#157 Tighten CSP by using nonces for inline scripts, move survey page outside of the service, add initial payment mop-up package
  README.md
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec-terminate.js
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/order-complete/route.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/server.js
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/payment-mop-up-job/src/__test__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/constants.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/payment-mop-up-job/src/processors/processor.js
Labels: enhancement

#159 Add support to create, update, get and query payment journals
  docker/resources/infrastructure/localstack/localstack-cfn.yml
  packages/connectors-lib/src/__tests__/document-client-decorator.spec.js
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/aws.js
  packages/connectors-lib/src/documentclient-decorator.js
  packages/connectors-lib/src/sales-api-connector.js
  packages/pocl-job/src/io/__tests__/db.spec.js
  packages/pocl-job/src/io/db.js
  packages/sales-api-service/README.md
  packages/sales-api-service/src/config.js
  packages/sales-api-service/src/schema/payment-journal.schema.js
  packages/sales-api-service/src/server/index.js
  packages/sales-api-service/src/server/routes/__tests__/payment-journals.spec.js
  packages/sales-api-service/src/server/routes/index.js
  packages/sales-api-service/src/server/routes/payment-journals.js
  packages/sales-api-service/src/services/paymentjournals/__tests__/payment-journals.sevice.spec.js
  packages/sales-api-service/src/services/paymentjournals/payment-journals.service.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-dlq.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-dlq.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sales-api-service/src/services/transactions/retrieve-transaction.js
Labels: enhancement
