Repository DEFRA/rod-licensing, pull requests merged in 2020-09, with the labels that each got.

#333 Allow server keep-alive to be configured for the frontend
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#326 Implement content changes from UCD
  packages/business-rules-lib/src/validators/__tests__/contact.spec.js
  packages/business-rules-lib/src/validators/contact.js
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
  packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk
  packages/gafl-webapp-service/src/pages/concessions/disability/route.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
  packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
  packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/contact/route.js
  packages/gafl-webapp-service/src/pages/contact/name/name.njk
  packages/gafl-webapp-service/src/pages/contact/name/route.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/licence-start-time.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/licence-start-time.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/no-licence-required.njk
  packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/route.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/order-complete/route.js
  packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/route.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/processors/__tests__/confirmation-pdf.spec.js
  packages/gafl-webapp-service/src/processors/confirmation-pdf.js
  packages/gafl-webapp-service/src/processors/licence-type-display.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#336 Fix: all indirect methods of selecting a 12 month licence
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/update-transaction.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/processors/date-and-time-display.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
Labels: bug

#338 Remove redundant redirects
  packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
  packages/gafl-webapp-service/src/__mocks__/test-utils-system.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/controller-handler.spec-2.js
  packages/gafl-webapp-service/src/handlers/controller-handler.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/route.js
  packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/disability-concession.spec.js
  packages/gafl-webapp-service/src/pages/concessions/disability/route.js
  packages/gafl-webapp-service/src/pages/concessions/disability/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/route.js
  packages/gafl-webapp-service/src/pages/contact/address/select/__tests__/address-select.spec.js
  packages/gafl-webapp-service/src/pages/contact/address/select/route.js
  packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
  packages/gafl-webapp-service/src/pages/contact/contact/route.js
  packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
  packages/gafl-webapp-service/src/pages/contact/name/result-function.js
  packages/gafl-webapp-service/src/pages/contact/name/route.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/newsletter.spec.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/licence-start-time.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/route.js
  packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/route.js
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/route.js
  packages/gafl-webapp-service/src/pages/payment/cancelled/route.js
  packages/gafl-webapp-service/src/pages/payment/failed/route.js
  packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/route.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
  packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
  packages/gafl-webapp-service/src/processors/concession-helper.js
  packages/gafl-webapp-service/src/routes/next-page.js
  packages/gafl-webapp-service/src/session-cache/__tests__/cache-manager.spec.js
Labels: enhancement

#339 Fix DoB format string
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
Labels: bug

#341 Remove redundant redirects from contact pages
  packages/gafl-webapp-service/src/pages/concessions/disability/result-function.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/result-function.js
  packages/gafl-webapp-service/src/pages/contact/address/select/result-function.js
  packages/gafl-webapp-service/src/pages/contact/contact/result-function.js
  packages/gafl-webapp-service/src/pages/contact/name/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/result-function.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
Labels: enhancement

#342 Bump package dependencies
  package-lock.json
  package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#324 Add encryption to session cookie
  docker/env/gafl_webapp.secrets.env
  docker/env/gafl_webapp_telesales.secrets.env
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/__mocks__/test-utils-system.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#343 Add dependabot v2 config, improve jest performance when running in travis
  .github/dependabot.yml
  .travis.yml
Labels: enhancement

#346 Add calendar control to licence start date page
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/assets/images/icon-calendar-2x.png
  packages/gafl-webapp-service/assets/sass/main.scss
  packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
  packages/gafl-webapp-service/build/gulpfile.cjs
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
Labels: enhancement

#352 Improve reliability and error handling of the POCL processor
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/connectors-lib/src/__tests__/document-client-decorator.spec.js
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/documentclient-decorator.js
  packages/connectors-lib/src/sales-api-connector.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
  packages/pocl-job/src/io/db.js
  packages/pocl-job/src/staging/__tests__/create-transactions.spec.js
  packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
  packages/pocl-job/src/staging/create-transactions.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sqs-receiver-service/src/__tests__/receiver.spec.js
Labels: enhancement

#345 Multiple frontend functional and content changes
  packages/business-rules-lib/src/validators/contact.js
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/gafl-webapp-service.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/disability/__tests__/disability-concession.spec.js
  packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk
  packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
  packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
  packages/gafl-webapp-service/src/pages/contact/contact/__tests__/contact.spec.js
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/contact/route.js
  packages/gafl-webapp-service/src/pages/contact/name/name.njk
  packages/gafl-webapp-service/src/pages/contact/newsletter/__tests__/newsletter.spec.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk
  packages/gafl-webapp-service/src/pages/errors/client-error.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/update-transaction.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/processors/confirmation-pdf.js
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/__tests__/cache-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
Labels: enhancement

#353 Filter non-iso compliant entries from countries list
  packages/gafl-webapp-service/src/processors/refdata-helper.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#356 Add debug capability to sales-api-connector
  packages/connectors-lib/src/sales-api-connector.js
  packages/pocl-job/src/staging/finalise-transactions.js
Labels: enhancement

#357 QA review of content
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
  packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
  packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
  packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/processors/refdata-helper.js
Labels: enhancement

#358 Fix calendar noshow on IE11
  packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Labels: bug

#361 Improvements to POCL loader to ensure process is resumable and improve efficiency
  packages/dynamics-lib/src/client/__tests__/cache.spec.js
  packages/dynamics-lib/src/client/cache.js
  packages/dynamics-lib/src/index.js
  packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/pocl-job/src/transform/bindings/pocl/licence/licence.bindings.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
  packages/sales-api-service/src/schema/validators/validators.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/server/server.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/retrieve-transaction.js
Labels: enhancement

#360 Improve the look of the calendar control
  packages/gafl-webapp-service/assets/sass/rod-licensing/_calendar.scss
  packages/gafl-webapp-service/build/gulpfile.cjs
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Labels: enhancement

#363 Revise contact name validation rules
  packages/business-rules-lib/src/index.js
  packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
  packages/business-rules-lib/src/validators/__tests__/permission.validators.spec.js
  packages/business-rules-lib/src/validators/contact.validators.js
  packages/business-rules-lib/src/validators/permission.validators.js
  packages/sales-api-service/src/schema/contact.schema.js
Labels: enhancement

#365 Fix length issue and add coverage
  packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
Labels: enhancement

#373 Rebrand PDF printout to be EA rather than GDS
  packages/gafl-webapp-service/assets/images/EA-logo_black.png
  packages/gafl-webapp-service/src/processors/__tests__/confirmation-pdf.spec.js
  packages/gafl-webapp-service/src/processors/confirmation-pdf.js
Labels: bug

#374 Changes in view of Andrew Hick's test report; IWTF-1436
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
  packages/gafl-webapp-service/src/pages/concessions/disability/disability-concession.njk
  packages/gafl-webapp-service/src/pages/contact/address/entry/address-entry.njk
  packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
  packages/gafl-webapp-service/src/pages/contact/address/lookup/route.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/newsletter/newsletter.njk
  packages/gafl-webapp-service/src/pages/errors/server-error.njk
  packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
  packages/gafl-webapp-service/src/pages/guidance/cookies.njk
  packages/gafl-webapp-service/src/pages/guidance/os-terms.njk
  packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
  packages/gafl-webapp-service/src/pages/guidance/refund-policy.njk
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
  packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk
  packages/gafl-webapp-service/src/pages/macros/standard-form.njk
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
  packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#378 Improve contact first/last name validation rules
  packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
  packages/business-rules-lib/src/validators/contact.validators.js
Labels: enhancement

#364 Bugfix: Campaign values not registering in GA
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
Labels: bug

#367 Bugfix: Junior Licences not tracked as sales
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
Labels: bug

#382 Use NODE_ENV in environment name of service-status output
  packages/sales-api-service/src/server/plugins/health.js
Labels: enhancement

#394 Bump dependencies for all packages
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
  packages/business-rules-lib/src/validators/__tests__/permission.validators.spec.js
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/dynamics-lib/src/entities/base.entity.js
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/handlers/authentication-handler.js
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/route.js
  packages/gafl-webapp-service/src/pages/concessions/disability/route.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/route.js
  packages/gafl-webapp-service/src/pages/contact/address/select/route.js
  packages/gafl-webapp-service/src/pages/contact/contact/route.js
  packages/gafl-webapp-service/src/pages/contact/name/route.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/route.js
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/route.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/config.js
  packages/sales-api-service/src/schema/authenticate.schema.js
  packages/sales-api-service/src/schema/concession-proof.schema.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/option-set.schema.js
  packages/sales-api-service/src/schema/payment-journal.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/permit.schema.js
  packages/sales-api-service/src/schema/reference-data.schema.js
  packages/sales-api-service/src/schema/staging-exception.schema.js
  packages/sales-api-service/src/schema/system-user.schema.js
  packages/sales-api-service/src/schema/transaction-file.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/validators.js
  packages/sales-api-service/src/server/routes/option-sets.js
  packages/sales-api-service/src/server/routes/reference-data.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
  packages/sqs-receiver-service/src/environment.js
Labels: dependencies

#383 Add load balancer cookies to the guidance page
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/pages/guidance/cookies.njk
  packages/gafl-webapp-service/src/routes/misc-routes.js
Labels: enhancement

#395 Adjust contact name validator to ensure 100% coverage
  README.md
  packages/business-rules-lib/src/validators/contact.validators.js
Labels: enhancement

#396 Fix content
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
Labels: enhancement
