Repository DEFRA/rod-licensing, pull requests merged in 2020-07, with the labels that each got.

#222 Bump project dependencies
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#225 Create release
  .travis.yml
  lerna.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
  scripts/travis_deploy.sh
Labels: enhancement

#227 Test release process
  .travis.yml
  CHANGELOG.md
  lerna.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
  scripts/travis_deploy.sh
Labels: enhancement

#228 Create new release
  CHANGELOG.md
  lerna.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
  scripts/travis_deploy.sh
Labels: enhancement

#229 Add ssl support
  docker/README.md
  docker/env/gafl_webapp_telesales.env
  docker/env/gafl_webapp_telesales.secrets.env
  docker/infrastructure.yml
  docker/resources/infrastructure/nginx/ca/ca.pem
  docker/resources/infrastructure/nginx/ssl/localhost.crt
  docker/resources/infrastructure/nginx/ssl/localhost.key
  docker/resources/infrastructure/nginx/templates/default.conf.template
  docker/services.dev.yml
  docker/services.yml
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/__tests__/server.telesales.spec.js
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/gafl-webapp-service.js
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/processors/payment.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
Labels: enhancement

#190 Implement Google Analytics
  docker/env/gafl_webapp.env
  package.json
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary-ga.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions-ga.spec.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
  packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
  packages/gafl-webapp-service/src/processors/analytics.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/__tests__/cache-decorator.spec.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/cache-decorator.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#236 Add support to authenticate with the configured redis instance
  packages/dynamics-lib/README.md
  packages/dynamics-lib/src/client/cache.js
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary-ga.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions-ga.spec.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/route.js
  packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
  packages/gafl-webapp-service/src/processors/analytics.js
  packages/gafl-webapp-service/src/processors/refdata-helper.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
Labels: enhancement

#239 Updates to support deployment into AWS
  Jenkinsfile
  docker/env/gafl_webapp.env
  docker/env/sales_api.env
  docker/env/sqs_receiver.env
  packages/sales-api-service/README.md
  packages/sales-api-service/src/config.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-dlq.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-dlq.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sales-api-service/src/services/transactions/retrieve-transaction.js
  packages/sqs-receiver-service/README.md
  packages/sqs-receiver-service/ecosystem.config.yml
Labels: enhancement

#238 Feature/easy renewal second phase
  CHANGELOG.md
  packages/business-rules-lib/src/constants.js
  packages/gafl-webapp-service/src/__tests__/server-fetch-public.js
  packages/gafl-webapp-service/src/handlers/authentication-handler.js
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/identity.spec.js
  packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/renewal-inactive.njk
  packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/route.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/update-transaction.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/renewal-start-date.njk
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/route.js
  packages/gafl-webapp-service/src/processors/date-and-time-display.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/routes/routes.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#243 Fix issue with CSRF token when a custom CSRF cookie name is set
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/server.js
Labels: bug

#254 Bump dependencies and tighten up husky commits/prettier linting configuration
  .prettierignore
  package-lock.json
  package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/server.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
Labels: dependencies

#241 Feature/fix backlink
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/src/__mocks__/test-utils.js
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/contact/contact/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/result-function.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
Labels: enhancement

#261 Fix issues in SQS receiver and Sales API connector
  packages/connectors-lib/src/sales-api-connector.js
  packages/pocl-job/src/staging/create-transactions.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/pocl-job/src/transport/ftp-to-s3.js
  packages/sales-api-service/src/services/contacts.service.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sales-api-service/src/services/transactions/retrieve-transaction.js
  packages/sqs-receiver-service/src/__mocks__/aws-sdk.js
  packages/sqs-receiver-service/src/__tests__/read-queue.spec.js
  packages/sqs-receiver-service/src/delete-messages.js
  packages/sqs-receiver-service/src/process-message.js
  packages/sqs-receiver-service/src/read-queue.js
  packages/sqs-receiver-service/src/receiver.js
Labels: bug

#260 Adjust licence validator, introduce disinfect library, refactoring improvements
  packages/business-rules-lib/src/validators/permission.js
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/__tests__/server-test-sanitize.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
  packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
  packages/gafl-webapp-service/src/plugins.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#262 Only delay polling SQS after several receive message requests return no messages
  packages/sqs-receiver-service/README.md
  packages/sqs-receiver-service/src/__mocks__/aws-sdk.js
  packages/sqs-receiver-service/src/__tests__/environment.spec.js
  packages/sqs-receiver-service/src/__tests__/receiver.spec.js
  packages/sqs-receiver-service/src/environment.js
  packages/sqs-receiver-service/src/read-queue.js
  packages/sqs-receiver-service/src/receiver.js
  packages/sqs-receiver-service/test-env.js
Labels: bug, enhancement

#265 Add fallback response parser method to Sales API connector and revise logging ouput
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/sales-api-connector.js
  packages/gafl-webapp-service/src/processors/payment.js
  packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js
  packages/pocl-job/src/pocl-processor.js
  packages/pocl-job/src/staging/pocl-data-staging.js
  packages/sales-api-service/src/server/routes/reference-data.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/services/contacts.service.js
  packages/sales-api-service/src/services/exceptions/exceptions.service.js
  packages/sales-api-service/src/services/paymentjournals/payment-journals.service.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sqs-receiver-service/src/__tests__/process-message.spec.js
  packages/sqs-receiver-service/src/delete-messages.js
  packages/sqs-receiver-service/src/process-message.js
Labels: enhancement

#267 Avoid attempting to consume the node-fetch response body twice
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/sales-api-connector.js
Labels: bug

#268 Network tuning parameters for AWS environment
  packages/connectors-lib/README.md
  packages/dynamics-lib/src/client/__tests__/cache.spec.js
  packages/sales-api-service/README.md
  packages/sales-api-service/src/config.js
  packages/sales-api-service/src/server/__tests__/index.spec.js
  packages/sales-api-service/src/server/index.js
Labels: enhancement

#269 Performance tuning improvements
  docker/env/pocl_job.env
  docker/env/sqs_receiver.env
  docker/infrastructure.yml
  packages/connectors-lib/README.md
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/client/cache.js
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/__tests__/base.entity.spec.js
  packages/dynamics-lib/src/entities/base.entity.js
  packages/dynamics-lib/src/index.js
  packages/dynamics-lib/src/optionset/global-option-set-definition.js
  packages/dynamics-lib/src/queries/__tests__/fulfilment.queries.spec.js
  packages/dynamics-lib/src/queries/__tests__/predefined-query.spec.js
  packages/fulfilment-job/src/staging/__tests__/create-part-files.spec.js
  packages/fulfilment-job/src/staging/__tests__/staging-common.spec.js
  packages/fulfilment-job/src/staging/staging-common.js
  packages/sales-api-service/src/__mocks__/test-data.js
  packages/sales-api-service/src/schema/option-set.schema.js
  packages/sales-api-service/src/server/plugins/health.js
  packages/sales-api-service/src/server/static/index.html
  packages/sales-api-service/src/services/__tests__/reference-data.service.spec.js
  packages/sales-api-service/src/services/exceptions/__tests__/exceptions.service.spec.js
  packages/sales-api-service/src/services/reference-data.service.js
  packages/sqs-receiver-service/README.md
  packages/sqs-receiver-service/src/__tests__/environment.spec.js
  packages/sqs-receiver-service/src/environment.js
  packages/sqs-receiver-service/test-env.js
Labels: enhancement

#272 Performance tuning of SQS integration and POCL job
  docker/env/sqs_receiver.env
  packages/pocl-job/src/staging/__tests__/create-transactions.spec.js
  packages/pocl-job/src/staging/__tests__/finalise-transactions.spec.js
  packages/pocl-job/src/staging/constants.js
  packages/pocl-job/src/staging/create-transactions.js
  packages/pocl-job/src/staging/finalise-transactions.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sqs-receiver-service/README.md
  packages/sqs-receiver-service/src/process-message.js
  packages/sqs-receiver-service/src/receiver.js
Labels: enhancement
