Repository DEFRA/rod-licensing, pull requests merged in 2020-04, with the labels that each got.

#45 Improve controller tests
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/__tests__/controller-handler.spec-2.js
  packages/gafl-webapp-service/src/handlers/__tests__/controller-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
  packages/gafl-webapp-service/src/handlers/controller-handler.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/handlers/result-functions.js
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/lib/__tests__/cache-decorator.spec.js
  packages/gafl-webapp-service/src/lib/__tests__/cache-manager.spec.js
  packages/gafl-webapp-service/src/lib/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/lib/__tests__/transaction-helper.spec.js
  packages/gafl-webapp-service/src/lib/add-permission.js
  packages/gafl-webapp-service/src/lib/cache-decorator.js
  packages/gafl-webapp-service/src/lib/cache-manager.js
  packages/gafl-webapp-service/src/lib/session-manager.js
  packages/gafl-webapp-service/src/lib/transaction-helper.js
  packages/gafl-webapp-service/src/misc/test-utils.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-check/__tests__/benefit-check.spec.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-check/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-check/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/__tests__/benefit-ni-number.spec.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/benefit-ni-number.njk
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/route.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/__tests__/blue-badge-check.spec.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/blue-badge-check.njk
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/route.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-number/__tests__/blue-badge-number.spec.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-number/blue-badge-number.njk
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-number/route.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-number/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
  packages/gafl-webapp-service/src/pages/concessions/junior-licence/__tests__/junior-licence.spec.js
  packages/gafl-webapp-service/src/pages/concessions/shared/concession-transaction.js
  packages/gafl-webapp-service/src/pages/contact/name/update-transaction.js
  packages/gafl-webapp-service/src/pages/error/error.njk
  packages/gafl-webapp-service/src/pages/error/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/no-licence-required/__tests__/no-licence-required.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/number-of-rods/update-transaction.js
  packages/gafl-webapp-service/src/pages/summary/__tests__/summary.spec.js
  packages/gafl-webapp-service/src/routes/__tests__/add-permission-route.spec.js
  packages/gafl-webapp-service/src/routes/add-permission-route.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
  packages/gafl-webapp-service/src/routes/routes.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#62 Update SQS receiver to handle all 2XX responses (inc 204 No Content) and use debug namespace
  docker/infrastructure.yml
  docker/resources/infrastructure/elasticmq.conf
  docker/resources/infrastructure/localstack-cfn.yml
  package-lock.json
  package.json
  packages/sqs-receiver-service/ecosystem.config.yml
  packages/sqs-receiver-service/package.json
  packages/sqs-receiver-service/src/__mocks__/node-fetch.js
  packages/sqs-receiver-service/src/__tests__/environment.spec.js
  packages/sqs-receiver-service/src/__tests__/process-message.spec.js
  packages/sqs-receiver-service/src/__tests__/show_queue-statistics.spec.js
  packages/sqs-receiver-service/src/delete-messages.js
  packages/sqs-receiver-service/src/environment.js
  packages/sqs-receiver-service/src/process-message.js
  packages/sqs-receiver-service/src/read-queue.js
  packages/sqs-receiver-service/src/receiver.js
  packages/sqs-receiver-service/src/show-queue-statistics.js
  packages/sqs-receiver-service/test-env.js
Labels: enhancement

#77 Add business-rules-lib package
  packages/business-rules-lib/.npmignore
  packages/business-rules-lib/LICENSE
  packages/business-rules-lib/README.md
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/business-rules-lib/src/__tests__/index.spec.js
  packages/business-rules-lib/src/index.js
  packages/business-rules-lib/src/validators/__tests__/contact.spec.js
  packages/business-rules-lib/src/validators/__tests__/permission.spec.js
  packages/business-rules-lib/src/validators/contact.js
  packages/business-rules-lib/src/validators/permission.js
Labels: enhancement

#87 Bump dependencies and add lerna.json to prettier ignore file
  .prettierignore
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#88 Separate endpoints for reference data entities and allow filtering on fields
  packages/dynamics-lib/src/entities/base.entity.js
  packages/dynamics-lib/src/optionset/global-option-set-definition.js
  packages/sales-api-service/__mocks__/test-data.js
  packages/sales-api-service/src/schema/reference-data.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/index.spec.js
  packages/sales-api-service/src/schema/validators/index.js
  packages/sales-api-service/src/server/__tests__/index.spec.js
  packages/sales-api-service/src/server/routes/__tests__/reference-data.spec.js
  packages/sales-api-service/src/server/routes/reference-data.js
  packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
  packages/sales-api-service/src/services/__tests__/reference-data.service.spec.js
  packages/sales-api-service/src/services/__tests__/transactions.service.spec.js
  packages/sales-api-service/src/services/permissions.service.js
  packages/sales-api-service/src/services/reference-data.service.js
  packages/sales-api-service/src/services/transactions.service.js
Labels: enhancement

#99 Update to reflect latest change to Dynamics schema, add initial support for recurring payments and transaction history
  docker/resources/infrastructure/localstack-cfn.yml
  packages/dynamics-lib/src/client/entity-manager.js
  packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/pocl-file.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/recurring-payment-instruction.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/transaction-journal.entity.spec.js
  packages/dynamics-lib/src/entities/__tests__/transaction.entity.spec.js
  packages/dynamics-lib/src/entities/base.entity.js
  packages/dynamics-lib/src/entities/permission.entity.js
  packages/dynamics-lib/src/entities/pocl-file.entity.js
  packages/dynamics-lib/src/entities/recurring-payment-instruction.entity.js
  packages/dynamics-lib/src/entities/recurring-payment.entity.js
  packages/dynamics-lib/src/entities/transaction-journal.entity.js
  packages/dynamics-lib/src/entities/transaction.entity.js
  packages/dynamics-lib/src/index.js
  packages/sales-api-service/__mocks__/test-data.js
  packages/sales-api-service/src/schema/concession-proof.schema.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/index.spec.js
  packages/sales-api-service/src/schema/validators/index.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/services/__tests__/transactions.service.spec.js
  packages/sales-api-service/src/services/reference-data.service.js
  packages/sales-api-service/src/services/transactions.service.js
  packages/sales-api-service/src/services/transactions/__tests__/transactions.service.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-dlq.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sales-api-service/src/services/transactions/transactions.service.js
Labels: enhancement

#103 Correct repo name and terminology to rod-licensing
  .travis.yml
  CONTRIBUTING.md
  Dockerfile.build
  README.md
  docker/resources/infrastructure/localstack-cfn.yml
  docker/services.build.yml
  docker/services.dev.yml
  docker/services.yml
  package-lock.json
  package.json
  packages/business-rules-lib/README.md
  packages/business-rules-lib/package.json
  packages/dynamics-lib/README.md
  packages/dynamics-lib/package.json
  packages/gafl-webapp-service/Dockerfile
  packages/gafl-webapp-service/Dockerfile.dev
  packages/gafl-webapp-service/package.json
  packages/sales-api-service/Dockerfile
  packages/sales-api-service/Dockerfile.dev
  packages/sales-api-service/README.md
  packages/sales-api-service/package.json
  packages/sales-api-service/src/server/plugins/swagger.js
  packages/sales-api-service/src/server/static/index.html
  packages/sqs-receiver-service/Dockerfile
  packages/sqs-receiver-service/Dockerfile.dev
  packages/sqs-receiver-service/package.json
  sonar-project.properties
Labels: bug

#106 Upgrade to node 14, bump dependencies and set pre-commit hook to only execute tests relating to source changes
  .travis.yml
  Dockerfile.base
  README.md
  package-lock.json
  package.json
  packages/business-rules-lib/package.json
  packages/dynamics-lib/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#107 Add dead letter queue handler and support for adding staging exceptions to Dynamics
  packages/dynamics-lib/src/entities/__tests__/staging-exception.entity.spec.js
  packages/dynamics-lib/src/entities/recurring-payment-instruction.entity.js
  packages/dynamics-lib/src/entities/staging-exception.entity.js
  packages/dynamics-lib/src/entities/transaction-journal.entity.js
  packages/dynamics-lib/src/index.js
  packages/sales-api-service/README.md
  packages/sales-api-service/src/schema/concession-proof.schema.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-dlq.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-dlq.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sales-api-service/src/services/transactions/retrieve-transaction.js
Labels: enhancement

#113 Improve shared business-rules and add concession/permit validation
  packages/business-rules-lib/src/index.js
  packages/business-rules-lib/src/util/__tests__/ages.spec.js
  packages/business-rules-lib/src/util/ages.js
  packages/business-rules-lib/src/validators/__tests__/contact.spec.js
  packages/business-rules-lib/src/validators/contact.js
  packages/dynamics-lib/src/entities/__tests__/recurring-payment-instruction.entity.spec.js
  packages/dynamics-lib/src/entities/recurring-payment-instruction.entity.js
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/address-lookup.spec.js
  packages/gafl-webapp-service/src/pages/contact/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/contact/date-of-birth/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/name/__tests__/name.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/__tests__/licence-start-date.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/index.spec.js
  packages/sales-api-service/src/schema/validators/index.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
  packages/sales-api-service/src/services/permissions.service.js
  packages/sales-api-service/src/services/reference-data.service.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#114 Resolve issue with permit/concession validator and complete post-payment validation
  package-lock.json
  package.json
  packages/business-rules-lib/src/validators/contact.js
  packages/dynamics-lib/src/__mocks__/TestEntity.js
  packages/dynamics-lib/src/__mocks__/adal-node.js
  packages/dynamics-lib/src/__mocks__/dynamics-web-api.js
  packages/dynamics-lib/src/__mocks__/option-set-data.json
  packages/dynamics-lib/src/client/__tests__/entity-manager.spec.js
  packages/dynamics-lib/src/entities/__tests__/base.entity.spec.js
  packages/gafl-webapp-service/package-lock.json
  packages/sales-api-service/__mocks__/adal-node.js
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/__mocks__/adal-node.js
  packages/sales-api-service/src/__mocks__/aws-sdk.js
  packages/sales-api-service/src/__mocks__/dynamics-web-api.js
  packages/sales-api-service/src/__mocks__/test-data.js
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/index.spec.js
  packages/sales-api-service/src/schema/validators/index.js
  packages/sales-api-service/src/server/routes/__tests__/reference-data.spec.js
  packages/sales-api-service/src/server/routes/__tests__/transactions.spec.js
  packages/sales-api-service/src/server/routes/transactions.js
  packages/sales-api-service/src/services/__tests__/contacts.service.spec.js
  packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
  packages/sales-api-service/src/services/__tests__/reference-data.service.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/finalise-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/finalise-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
  packages/sqs-receiver-service/src/__tests__/sqs-receiver-service.spec.js
Labels: enhancement
