Repository DEFRA/rod-licensing, pull requests merged in 2020-10, with the labels that each got.

#397 Amend accept cookies cookie name
  packages/gafl-webapp-service/src/pages/layout/layout.njk
Labels: bug

#398 Implement distributed locks to prevent concurrent execution of ETL tasks
  package-lock.json
  package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/connectors-lib/src/__tests__/distributed-lock.spec.js
  packages/connectors-lib/src/connectors.js
  packages/connectors-lib/src/distributed-lock.js
  packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
  packages/fulfilment-job/src/fulfilment-processor.js
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-ga.spec.js
  packages/gafl-webapp-service/src/server.js
  packages/payment-mop-up-job/src/__test__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/payment-mop-up-job/src/processors/__tests__/processor.spec.js
  packages/pocl-job/src/__tests__/pocl-processor.spec.js
  packages/pocl-job/src/pocl-processor.js
  packages/pocl-job/src/transport/s3-to-local.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: enhancement

#403 Tweak fulfilment to ensure duration/equipment compatible with old service
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/fulfilment-job/src/transform/__tests__/fulfilment-transform.spec.js
  packages/fulfilment-job/src/transform/fulfilment-transform.js
Labels: enhancement

#404 Ensure date validator schemas are created at the time of use
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/licence-to-start.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/route.js
Labels: bug

#406 Change error messages on name page
  packages/gafl-webapp-service/src/pages/contact/name/name.njk
Labels: enhancement

#408 Updates and fixes to the ETL tasks
  docker/env/fulfilment_job.env
  packages/connectors-lib/src/__tests__/distributed-lock.spec.js
  packages/connectors-lib/src/distributed-lock.js
  packages/dynamics-lib/src/client/__tests__/cache.spec.js
  packages/dynamics-lib/src/client/cache.js
  packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
  packages/fulfilment-job/src/fulfilment-processor.js
  packages/fulfilment-job/src/staging/__tests__/create-part-files.spec.js
  packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
  packages/fulfilment-job/src/staging/create-part-files.js
  packages/fulfilment-job/src/staging/deliver-fulfilment-files.js
  packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/pocl-job/src/__tests__/pocl-processor.spec.js
  packages/pocl-job/src/pocl-processor.js
Labels: enhancement

#409 Handle cases where no country available on contact record being fulfilled
  packages/fulfilment-job/src/transform/fulfilment-transform.js
Labels: enhancement

#413 Add section to privacy policy regarding use of Google Analytics
  packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
Labels: enhancement

#412 Update permission number generator to use a sequence and add a checksum
  package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/__mocks__/ioredis.js
  packages/sales-api-service/src/services/__tests__/ioredis.spec.js
  packages/sales-api-service/src/services/__tests__/permissions.service.spec.js
  packages/sales-api-service/src/services/ioredis.service.js
  packages/sales-api-service/src/services/permissions.service.js
  sonar-project.properties
Labels: enhancement

#422 Reduce default time for mop-up eligibility to 60 minutes
  packages/payment-mop-up-job/README.md
  packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/constants.js
Labels: enhancement

#423 Use dates in local time for licence start date calculation/validation in the frontend.
  packages/gafl-webapp-service/src/handlers/authentication-handler.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/update-transaction.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/update-transaction.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/processors/api-transaction.js
  packages/gafl-webapp-service/src/processors/concession-helper.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
Labels: bug

#424 Bump dependencies
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#425 Improve versioning control in travis deploy script when merging to master
  scripts/travis/deploy.sh
Labels: enhancement

#426 Changes to the accessibility statement
  packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
Labels: enhancement

#428 Fix bug in travis deploy script
  scripts/travis/deploy.sh
Labels: bug

#430 Relax validation rules for Post Office sales
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
  packages/sales-api-service/src/schema/validators/validators.js
Labels: enhancement

#431 SEMVER-MINOR: Relax the validation rules for Post Office sales
  CHANGELOG.md
  lerna.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/schema/__tests__/transaction.schema.spec.js
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sales-api-service/src/schema/permission.schema.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/schema/validators/__tests__/validators.spec.js
  packages/sales-api-service/src/schema/validators/validators.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: enhancement

#432 Relax address validation rules for P.O. and correct sales date
  packages/pocl-job/src/transport/ftp-to-s3.js
  packages/sales-api-service/src/schema/contact.schema.js
Labels: enhancement

#433 SEMVER-MINOR: Relax address validation rules for P.O. and correct sales date
  CHANGELOG.md
  lerna.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/pocl-job/src/transport/ftp-to-s3.js
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sales-api-service/src/schema/contact.schema.js
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: enhancement

#439 Add airbrake support all services
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/connectors-lib/src/__tests__/airbrake.spec.js
  packages/connectors-lib/src/airbrake.js
  packages/connectors-lib/src/connectors.js
  packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
  packages/fulfilment-job/src/fulfilment-processor.js
  packages/gafl-webapp-service/src/__tests__/gafl-webapp-service.spec.js
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/handlers/error-handler.js
  packages/gafl-webapp-service/src/server.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/pocl-job/src/__tests__/pocl-processor.spec.js
  packages/pocl-job/src/pocl-processor.js
  packages/sales-api-service/src/server/__tests__/server.spec.js
  packages/sales-api-service/src/server/server.js
  packages/sqs-receiver-service/ecosystem.config.yml
  packages/sqs-receiver-service/src/__tests__/sqs-receiver-service.spec.js
  packages/sqs-receiver-service/src/sqs-receiver-service.js
Labels: enhancement

#438 Added telesales new customer button (#438)
  packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/pages/layout/layout.njk
  packages/gafl-webapp-service/src/pages/renewals/renewal-start-date/__tests__/renewal-start-date.spec.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/gafl-webapp-service/src/server.js
Labels: enhancement

#414 Add moto flag for telesales
  packages/gafl-webapp-service/src/processors/payment.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
Labels: enhancement

#451 Fix ioredis preventing shutdown & use spec-compliant interrupt exit-code
  packages/connectors-lib/src/distributed-lock.js
  packages/fulfilment-job/src/__tests__/fulfilment-processor.spec.js
  packages/fulfilment-job/src/fulfilment-processor.js
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/server.js
  packages/payment-mop-up-job/src/__tests__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/pocl-job/src/__tests__/pocl-processor.spec.js
  packages/pocl-job/src/pocl-processor.js
  packages/sales-api-service/src/server/__tests__/server.spec.js
  packages/sales-api-service/src/server/server.js
  packages/sqs-receiver-service/src/__tests__/sqs-receiver-service.spec.js
  packages/sqs-receiver-service/src/sqs-receiver-service.js
Labels: bug

#454 Ensure cache manager calls disconnect on ioredis when terminating
  packages/dynamics-lib/src/client/__tests__/cache.spec.js
  packages/dynamics-lib/src/client/cache.js
Labels: bug

#458 Enable x-domain analytics tracking & persist attribution between sessions
  packages/gafl-webapp-service/src/__tests__/server-ga-integration.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/handlers/new-session-handler.js
  packages/gafl-webapp-service/src/plugins.js
  packages/gafl-webapp-service/src/processors/__tests__/analytics.spec.js
  packages/gafl-webapp-service/src/processors/analytics.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
Labels: enhancement
