Repository DEFRA/rod-licensing, pull requests merged in 2020-06, with the labels that each got.

#171 Add mop-up job to reconcile payments with GOV.UK Pay
  packages/business-rules-lib/src/constants.js
  packages/connectors-lib/README.md
  packages/connectors-lib/src/__tests__/govuk-pay-api.spec.js
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/connectors.js
  packages/connectors-lib/src/govuk-pay-api.js
  packages/connectors-lib/src/sales-api-connector.js
  packages/gafl-webapp-service/README.md
  packages/gafl-webapp-service/package.json
  packages/gafl-webapp-service/src/__mocks__/data/concessions.js
  packages/gafl-webapp-service/src/__mocks__/data/defra-country.js
  packages/gafl-webapp-service/src/__mocks__/data/permit-concessions.js
  packages/gafl-webapp-service/src/__mocks__/data/permits.js
  packages/gafl-webapp-service/src/__mocks__/mock-journeys.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-sales-api-failure.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/route.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/route.js
  packages/gafl-webapp-service/src/pages/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/payment/failed/route.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/licence-summary.spec.js
  packages/gafl-webapp-service/src/pages/terms-and-conditions/__tests__/terms-and-conditions.spec.js
  packages/gafl-webapp-service/src/processors/api-transaction.js
  packages/gafl-webapp-service/src/processors/countries-helper.js
  packages/gafl-webapp-service/src/processors/filter-permits.js
  packages/gafl-webapp-service/src/processors/mapping-constants.js
  packages/gafl-webapp-service/src/processors/payment.js
  packages/gafl-webapp-service/src/processors/refdata-helper.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
  packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js
  packages/gafl-webapp-service/src/services/sales-api/sales-api-service.js
  packages/payment-mop-up-job/LICENSE
  packages/payment-mop-up-job/README.md
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/payment-mop-up-job/src/__test__/payment-mop-up-job.spec.js
  packages/payment-mop-up-job/src/constants.js
  packages/payment-mop-up-job/src/payment-mop-up-job.js
  packages/payment-mop-up-job/src/processors/__test__/processor.spec.js
  packages/payment-mop-up-job/src/processors/processor.js
  packages/sales-api-service/src/schema/payment-journal.schema.js
Labels: enhancement

#180 Various display changes documented in IWTF-1104
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/name/name.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/licence-start-date.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/route.js
Labels: enhancement

#181 Fix configuration error in POCL docker-compose definition
  docker/services.yml
Labels: bug

#182 Add docker support to the payment mopup service
  docker/env/payment_mop_up_job.env
  docker/services.build.yml
  docker/services.dev.yml
  docker/services.yml
  packages/payment-mop-up-job/Dockerfile
  packages/payment-mop-up-job/Dockerfile.dev
Labels: enhancement

#188 Moved dob to licence summary and update contact preferences to reflect latest design
  packages/gafl-webapp-service/assets/sass/rod-licensing/_general.scss
  packages/gafl-webapp-service/src/handlers/result-functions.js
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/date-of-birth.spec.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/date-of-birth.njk
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/route.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/contact/contact.njk
  packages/gafl-webapp-service/src/pages/contact/contact/route.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/summary/contact-summary/contact-summary.njk
  packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/routes/routes.js
Labels: enhancement

#189 Static files failing to serve
  packages/gafl-webapp-service/src/routes/static-routes.js
Labels: bug

#196 Remove jest-each as this is natively supported by jest
  package-lock.json
  package.json
  packages/business-rules-lib/src/validators/__tests__/contact.spec.js
  packages/business-rules-lib/src/validators/__tests__/permission.spec.js
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/__tests__/licence-length.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-time/__tests__/licence-start-time.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/__tests__/licence-type.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/number-of-rods/__tests__/number-of-rods.spec.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/pocl-job/src/staging/__tests__/pocl-data-staging.spec.js
  packages/sales-api-service/src/server/__tests__/index.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
Labels: enhancement

#197 Bump dependencies, remove aws-sdk as dependency for packages using connectors-lib
  package-lock.json
  package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#198 Revise git commit hooks to fix issues with sftp keys and secrets.env files
  package.json
Labels: enhancement

#200 Ensure errors uploading fulfilment data to S3 and FTP are properly trapped
  packages/fulfilment-job/src/__mocks__/ssh2-sftp-client.js
  packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
  packages/fulfilment-job/src/staging/deliver-fulfilment-files.js
  packages/fulfilment-job/src/transport/__tests__/ftp.spec.js
  packages/fulfilment-job/src/transport/__tests__/s3.spec.js
  packages/fulfilment-job/src/transport/ftp.js
  packages/fulfilment-job/src/transport/s3.js
Labels: enhancement

#201 Add test coverage for easy renewals /renew redirect handler
  CHANGELOG.md
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
  packages/gafl-webapp-service/src/uri.js
Labels: bug

#202 Allow senior and juniors access to disabled concessions
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/controller-handler.js
  packages/gafl-webapp-service/src/pages/concessions/benefit-check/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/blue-badge-check/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/result-function.js
  packages/gafl-webapp-service/src/pages/concessions/junior-licence/__tests__/junior-licence.spec.js
  packages/gafl-webapp-service/src/pages/concessions/junior-licence/result-function.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/result-function.js
  packages/gafl-webapp-service/src/pages/contact/contact/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-start-date/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/result-function.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/contact-summary.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/processors/__tests__/concession-helper-spec.js
  packages/gafl-webapp-service/src/processors/concession-helper.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
Labels: enhancement

#203 Add an NI number validator
  packages/business-rules-lib/src/validators/__tests__/contact.spec.js
  packages/business-rules-lib/src/validators/contact.js
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/benefit-ni-number.njk
  packages/gafl-webapp-service/src/pages/concessions/benefit-ni-number/route.js
Labels: enhancement

#204 Changes to renewals procedure: fixes and changes around non-mandatory fields
  packages/gafl-webapp-service/src/pages/contact/address/entry/__tests__/address-entry-spec.js
  packages/gafl-webapp-service/src/pages/contact/address/entry/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/contact/update-transaction.js
  packages/gafl-webapp-service/src/pages/contact/newsletter/update-transaction.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/__mocks__/data/authentication-result.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
  packages/sales-api-service/src/schema/contact.schema.js
Labels: bug
