Repository DEFRA/rod-licensing, pull requests merged in 2022-03, with the labels that each got.

#1120 Follow-up update to licence conditions text
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: bug

#1119 Update how should we contact person page
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1122 Update to licence details link to be more generic
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1123 Replace footmarks with apostrophes
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1126 Fix for incorrect title on confirmation method page
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: bug

#1128 Update find address hint text to be consistent
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1124 Feature/iwtf 2369 console error
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
Labels: bug

#1083 Update dependencies - TO BE MERGED IN AFTER BOBO RELEASE
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/business-rules-lib/package.json
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/dynamics-lib/package-lock.json
  packages/dynamics-lib/package.json
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/package.json
  packages/payment-mop-up-job/package-lock.json
  packages/payment-mop-up-job/package.json
  packages/pocl-job/package-lock.json
  packages/pocl-job/package.json
  packages/sales-api-service/package-lock.json
  packages/sales-api-service/package.json
  packages/sqs-receiver-service/package-lock.json
  packages/sqs-receiver-service/package.json
Labels: dependencies

#1101 Upgrade airbrake 3 - TO BE MERGED IN AFTER BOBO RELEASE
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
  packages/connectors-lib/src/__tests__/airbrake.spec.js
  packages/connectors-lib/src/airbrake.js
Labels: dependencies

#1125 Multibuy - add another licence
  packages/gafl-webapp-service/src/__mocks__/request.js
  packages/gafl-webapp-service/src/handlers/result-functions.js
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/__tests__/result-function.spec.js
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/add-licence.njk
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/result-function.js
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/route.js
  packages/gafl-webapp-service/src/pages/multibuy/view-licences/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/multibuy/view-licences/route.js
  packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/routes/routes.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#1161 Feature/iwtf 2386 multibuy add another
  packages/gafl-webapp-service/src/pages/multibuy/add-licence/add-licence.njk
Labels: enhancement

#1168 Update documentation on volumes
  docker/README.md
Labels: documentation

#1166 Remove aws-sdk dependency from main package.json
  package-lock.json
  package.json
  packages/connectors-lib/src/__mocks__/aws-sdk.js
  packages/fulfilment-job/src/__mocks__/aws-sdk.js
  packages/pocl-job/src/__mocks__/aws-sdk.js
  packages/sales-api-service/src/__mocks__/aws-sdk.js
  packages/sqs-receiver-service/src/__mocks__/aws-sdk.js
Labels: dependencies

#1133 Update address lookup capital formatting
  packages/gafl-webapp-service/assets/sass/main.scss
  packages/gafl-webapp-service/assets/sass/rod-licensing/_address.scss
  packages/gafl-webapp-service/src/pages/contact/address/select/address-select.njk
  packages/gafl-webapp-service/src/services/address-lookup/__tests__/address-lookup-service.spec.js
  packages/gafl-webapp-service/src/services/address-lookup/address-lookup-service.js
Labels: enhancement
