Repository DEFRA/rod-licensing, pull requests merged in 2022-05, with the labels that each got.

#1259 Amend placement of warning on Licence conditions page
  packages/gafl-webapp-service/src/pages/terms-and-conditions/terms-and-conditions.njk
Labels: enhancement

#1255 International postcodes not accepted
  packages/business-rules-lib/src/validators/__tests__/contact.validators.spec.js
  packages/business-rules-lib/src/validators/contact.validators.js
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
Labels: bug

#1265 Do you want to go paperless? - welsh translation
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1260 Welsh translation - contact reminders
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1213 Welsh Translation - How long want licence for
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/licence-details/licence-length/licence-length.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-type/licence-type.njk
  packages/gafl-webapp-service/src/pages/macros/licence-type-summary.njk
  packages/gafl-webapp-service/src/pages/macros/pricing-summary.njk
Labels: enhancement

#1270 Is your email address correct - welsh translation
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/pages/contact/digital-licence/check-confirmation-contact/check-confirmation-contact.njk
Labels: enhancement

#1275 Welsh lang update for BOBO man address entry page
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1276 Welsh lang update BOBO how should we contact them page
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1226 Lang=cy is not persisting across pages
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/contact/address/lookup/route.js
  packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
  packages/gafl-webapp-service/src/pages/guidance/cookies.njk
  packages/gafl-webapp-service/src/pages/guidance/os-terms.njk
  packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
  packages/gafl-webapp-service/src/pages/guidance/refund-policy.njk
  packages/gafl-webapp-service/src/processors/__tests__/uri-helper.spec.js
  packages/gafl-webapp-service/src/processors/uri-helper.js
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes-cookies.spec.js
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes-handlers.spec.js
  packages/gafl-webapp-service/src/routes/__tests__/next-page.spec.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/routes/next-page.js
  packages/gafl-webapp-service/src/server.js
Labels: bug

#1277 Update welsh lang for BOBO go paperless page
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1266 Feature/iwtf 2838 renew international licence
  packages/gafl-webapp-service/src/handlers/authentication-handler.js
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
Labels: bug

#1280 Is the phone number correct - welsh translation
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1284 Version updates
  packages/gafl-webapp-service/package-lock.json
  packages/sales-api-service/package-lock.json
Labels: dependencies

#1289 Update OS Crown and Copyright
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
  packages/gafl-webapp-service/src/pages/layout/layout.njk
Labels: enhancement

#1251 Multibuy - saving input details
  packages/gafl-webapp-service/src/handlers/__tests__/multibuy-for-you-handler.spec.js
  packages/gafl-webapp-service/src/handlers/multibuy-for-you-handler.js
  packages/gafl-webapp-service/src/handlers/result-functions.js
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/result-function.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/result-function.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/summary/contact-summary/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
Labels: enhancement

#1301 Welsh - BOBO how long do they want licence for
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1297 Welsh - how do you want fishing licence confirmation
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1298 Welsh - where send licence
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1299 Welsh lang BOBO update where to send licence page
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1304 Fix failing test on short licence error page update
  packages/gafl-webapp-service/src/pages/renewals/renewal-inactive/__tests__/route.spec.js
Labels: bug

#1307 Welsh - refund policy
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1311 Welsh - how contact with reminders
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1312 Welsh - Accessibility Statement
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/guidance/accessibility-statement.njk
Labels: enhancement

#1306 Amend error page after going back during payment
  packages/gafl-webapp-service/src/handlers/__tests__/error-handler.spec.js
  packages/gafl-webapp-service/src/handlers/error-handler.js
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/errors/client-error.njk
Labels: enhancement
