Repository DEFRA/rod-licensing, pull requests merged in 2022-02, with the labels that each got.

#1053 Reword fishing licence confirmation
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1031 Feature/iwtf 2590 attribution redirect
  packages/gafl-webapp-service/src/constants.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#1056 Feature/iwtf 2647 easy renewal content
  packages/gafl-webapp-service/src/processors/__tests__/renewals-write-cache.spec.js
  packages/gafl-webapp-service/src/processors/renewals-write-cache.js
Labels: enhancement

#1045 Alter env var structure
  docker/README.md
  docker/env/fulfilment_job.env.example
  docker/env/fulfilment_job.secrets.env.example
  docker/env/gafl_webapp.env.example
  docker/env/gafl_webapp.secrets.env.example
  docker/env/gafl_webapp_telesales.env.example
  docker/env/gafl_webapp_telesales.secrets.env.example
  docker/env/payment_mop_up_job.env.example
  docker/env/payment_mop_up_job.secrets.env.example
  docker/env/pocl_job.env.example
  docker/env/sales_api.env.example
  docker/env/sales_api.secrets.env.example
  docker/env/sqs_receiver.env.example
  docker/services.dev.yml
  docker/services.yml
Labels: enhancement

#1057 Welsh translation for date of birth
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1069 Update readme for env var structure
  docker/README.md
Labels: enhancement

#1070 Welsh translation - eligible
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1071 Specify charge transaction id in import file
  packages/business-rules-lib/src/constants.js
  packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/transaction.bindings.spec.js
  packages/pocl-job/src/transform/bindings/pocl/transaction/transaction.bindings.js
  packages/sales-api-service/src/schema/transaction.schema.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#1075 Fix attribution redirect for renewals
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
Labels: bug

#1085 Fix for back button from address lookup page
  packages/gafl-webapp-service/src/routes/__tests__/back-links.spec.js
  packages/gafl-webapp-service/src/routes/journey-definition.js
Labels: bug

#1067 Upgrade airbrake in connectors-lib
  packages/connectors-lib/package-lock.json
  packages/connectors-lib/package.json
Labels: dependencies

#1086 Update link to annual fishery report
  packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/licence-fulfilment.njk
Labels: enhancement

#1088 Update privacy policy
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
Labels: enhancement

#1087 Upgrade OpenPGP Library
  packages/fulfilment-job/package-lock.json
  packages/fulfilment-job/package.json
  packages/fulfilment-job/src/staging/__tests__/deliver-fulfilment-files.spec.js
  packages/fulfilment-job/src/staging/deliver-fulfilment-files.js
Labels: enhancement

#1092 Feature/iwtf 2744 content issue
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: bug

#1074 Easy renewals vanity URL
  packages/gafl-webapp-service/src/handlers/__tests__/url-handler.spec.js
  packages/gafl-webapp-service/src/handlers/url-handler.js
Labels: enhancement

#1095 Update prettier dependency
  package-lock.json
  package.json
Labels: dependencies

#1094 Alternate image text for calendar
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Labels: bug

#1093 Remove additional logging
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/__tests__/update-transaction.spec.js
  packages/gafl-webapp-service/src/pages/concessions/date-of-birth/update-transaction.js
Labels: enhancement

#1104 Update text on licence complete confirmation page
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
Labels: enhancement

#1110 Update licence details page
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/order-complete/licence-details/licence-details.njk
Labels: enhancement

#1111 Update order complete page
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement
