Repository DEFRA/rod-licensing, pull requests merged in 2023-01, with the labels that each got.

#1591 Update Welsh translations for client errors
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1590 Add Welsh translations to server error messages
  packages/gafl-webapp-service/src/locales/cy.json
Labels: enhancement

#1596 Update Ubuntu version used for GH Actions builds
  .github/workflows/build.yml
Labels: dependencies

#1580 Refactor redirects to automatically use correct language
  packages/gafl-webapp-service/src/__tests__/server.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-happy-path.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/agreed-handler-payment-failure.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/analytics-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/attribution-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/authentication-handler.redirect.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/new-session-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/oidc-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/page-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/renewal-start-date-validation-handler.spec.js
  packages/gafl-webapp-service/src/handlers/__tests__/renewals-friendly-url-handler.spec.js
  packages/gafl-webapp-service/src/handlers/agreed-handler.js
  packages/gafl-webapp-service/src/handlers/analytics-handler.js
  packages/gafl-webapp-service/src/handlers/attribution-handler.js
  packages/gafl-webapp-service/src/handlers/authentication-handler.js
  packages/gafl-webapp-service/src/handlers/controller-handler.js
  packages/gafl-webapp-service/src/handlers/new-session-handler.js
  packages/gafl-webapp-service/src/handlers/oidc-handler.js
  packages/gafl-webapp-service/src/handlers/page-handler.js
  packages/gafl-webapp-service/src/handlers/renewal-start-date-validation-handler.js
  packages/gafl-webapp-service/src/handlers/renewals-friendly-url-handler.js
  packages/gafl-webapp-service/src/routes/__tests__/misc-routes.spec.js
  packages/gafl-webapp-service/src/routes/__tests__/next-page.spec.js
  packages/gafl-webapp-service/src/routes/misc-routes.js
  packages/gafl-webapp-service/src/routes/next-page.js
  packages/gafl-webapp-service/src/server.js
  packages/gafl-webapp-service/src/session-cache/__tests__/session-manager.spec.js
  packages/gafl-webapp-service/src/session-cache/session-manager.js
Labels: enhancement

#1600 Fix typos in Welsh translation
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/errors/client-error.njk
Labels: enhancement

#1593 Notification banner
  docker/env/gafl_webapp.env.example
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/route.js
  packages/gafl-webapp-service/src/pages/macros/notification-banner.njk
  packages/gafl-webapp-service/src/pages/macros/standard-form.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/licence-summary.njk
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
Labels: enhancement

#1578 Name page is not autofilled when buying second licence for self
  packages/gafl-webapp-service/src/pages/contact/name/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/contact/name/__tests__/update-transaction.spec.js
  packages/gafl-webapp-service/src/pages/contact/name/name.njk
  packages/gafl-webapp-service/src/pages/contact/name/route.js
Labels: bug

#1598 Use permission start date to calculate price
  packages/gafl-webapp-service/src/processors/__tests__/__snapshots__/pricing-summary.spec.js.snap
  packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
  packages/gafl-webapp-service/src/processors/pricing-summary.js
Labels: enhancement

#1605 Simplify confirmation page
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
Labels: enhancement

#1603 Stop language parameters from being duplicated in URLs
  packages/gafl-webapp-service/src/processors/__tests__/uri-helper.spec.js
  packages/gafl-webapp-service/src/processors/uri-helper.js
Labels: enhancement

#1602 Fix translation and title errors on server error page
  packages/gafl-webapp-service/src/handlers/__tests__/error-handler.spec.js
  packages/gafl-webapp-service/src/handlers/error-handler.js
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/errors/server-error.njk
Labels: enhancement

#1595 Multibuy - delete licence page
  packages/gafl-webapp-service/src/handlers/update-transaction-functions.js
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/__snapshots__/route.spec.js.snap
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/remove-licence.njk
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/route.js
  packages/gafl-webapp-service/src/pages/multibuy/remove-licence/update-transaction.js
  packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk
  packages/gafl-webapp-service/src/routes/journey-definition.js
  packages/gafl-webapp-service/src/routes/routes.js
  packages/gafl-webapp-service/src/uri.js
Labels: enhancement

#1608 Add getPrice to Permission
  packages/business-rules-lib/src/index.js
  packages/business-rules-lib/src/util/__tests__/permissions.spec.js
  packages/business-rules-lib/src/util/permissions.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
Labels: enhancement

#1612 Error after Ts&Cs page purchasing licence
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
Labels: bug

#1613 Update transaction journal to use new price
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
  packages/sales-api-service/src/services/transactions/__tests__/create-transaction.spec.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/create-transaction.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#1616 Price incorrect on Licence Summary page
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
  packages/gafl-webapp-service/src/processors/__tests__/price-display.spec.js
  packages/gafl-webapp-service/src/processors/price-display.js
Labels: bug

#1618 Remove double pound sign on order complete page
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/order-complete.njk
Labels: bug
