Repository DEFRA/rod-licensing, pull requests merged in 2024-12, with the labels that each got.

#2085 FTP POCL references
  docker/env/pocl_job.env.example
  packages/pocl-job/README.md
Labels: enhancement

#2082 Rename createRecurringPayment to clarify it creates agreements
  packages/connectors-lib/src/__tests__/govuk-pay-api.spec.js
  packages/connectors-lib/src/govuk-pay-api.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
  packages/gafl-webapp-service/src/services/payment/govuk-pay-service.js
Labels: enhancement

#2088 Change length link junior licence
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/__snapshots__/route.spec.js.snap
  packages/gafl-webapp-service/src/pages/summary/licence-summary/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/summary/licence-summary/route.js
Labels: bug

#2081 Create RP Record in CRM
  packages/dynamics-lib/src/entities/__tests__/recurring-payment.entity.spec.js
  packages/dynamics-lib/src/entities/recurring-payment.entity.js
  packages/sales-api-service/src/services/__tests__/__snapshots__/recurring-payments.service.spec.js.snap
  packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
  packages/sales-api-service/src/services/recurring-payments.service.js
  packages/sales-api-service/src/services/transactions/__tests__/process-transaction-queue.spec.js
  packages/sales-api-service/src/services/transactions/process-transaction-queue.js
Labels: enhancement

#2089 Update Lerna to 5.6.2
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/connectors-lib/package-lock.json
  packages/dynamics-lib/package-lock.json
  packages/fulfilment-job/package-lock.json
  packages/gafl-webapp-service/package-lock.json
  packages/payment-mop-up-job/package-lock.json
  packages/pocl-job/package-lock.json
  packages/recurring-payments-job/package-lock.json
  packages/sales-api-service/package-lock.json
  packages/sqs-receiver-service/package-lock.json
Labels: dependencies

#2092 Fix RP creation bug
  packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
  packages/sales-api-service/src/services/recurring-payments.service.js
Labels: bug

#2093 Fix DOB message in Welsh
  packages/gafl-webapp-service/src/locales/cy.json
Labels: bug

#2094 Licence to start error not in error summary
  packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/licence-to-start.njk
Labels: bug

#2091 Update activity in CRM
  packages/dynamics-lib/src/queries/__tests__/activity.queries.spec.js
  packages/dynamics-lib/src/queries/activity.queries.js
Labels: enhancement

#2095 Missing inline error on renewals id page
  packages/gafl-webapp-service/src/pages/renewals/identify/__tests__/route.spec.js
  packages/gafl-webapp-service/src/pages/renewals/identify/identify.njk
  packages/gafl-webapp-service/src/pages/renewals/identify/route.js
Labels: bug

#2099 Payment edge case 2025
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/processors/__tests__/pricing-summary.spec.js
  packages/gafl-webapp-service/src/processors/pricing-summary.js
Labels: enhancement

#2098 New price increase
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/guidance/new-prices.njk
Labels: enhancement

#2096 Update order complete page RCP logic
  packages/dynamics-lib/src/entities/__tests__/permission.entity.spec.js
  packages/dynamics-lib/src/entities/permission.entity.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
  packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
Labels: enhancement
