Repository DEFRA/rod-licensing, pull requests merged in 2024-06, with the labels that each got.

#1969 Corrected accessibility statement
  package-lock.json
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
Labels: enhancement

#1953 Update Node version prerequisite in README
  README.md
Labels: documentation

#1972 dependencies error
  package-lock.json
Labels: bug

#1974 update lerna
  package-lock.json
  package.json
  packages/business-rules-lib/package-lock.json
  packages/connectors-lib/package-lock.json
  packages/dynamics-lib/package-lock.json
  packages/fulfilment-job/package-lock.json
  packages/gafl-webapp-service/package-lock.json
  packages/payment-mop-up-job/package-lock.json
  packages/pocl-job/package-lock.json
  packages/recurring-payments-job/package-lock.json
  packages/sales-api-service/package-lock.json
  packages/sqs-receiver-service/package-lock.json
Labels: enhancement

#1977 Add new query based on full reference number
  packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
  packages/dynamics-lib/src/queries/permission.queries.js
Labels: enhancement

#1978 Add new route to Sales API connector
  packages/connectors-lib/src/__tests__/sales-api-connector.spec.js
  packages/connectors-lib/src/sales-api-connector.js
Labels: enhancement

#1957 Recurring payments job sets up new permissions in DynamoDb
  packages/recurring-payments-job/package-lock.json
  packages/recurring-payments-job/package.json
  packages/recurring-payments-job/src/__tests__/recurring-payments-processor.spec.js
  packages/recurring-payments-job/src/recurring-payments-processor.js
  packages/sales-api-service/src/schema/__tests__/renewals.schema.spec.js
  packages/sales-api-service/src/schema/renewals.schema.js
  packages/sales-api-service/src/server/routes/__tests__/__snapshots__/renewals.spec.js.snap
  packages/sales-api-service/src/server/routes/__tests__/renewals.spec.js
  packages/sales-api-service/src/server/routes/index.js
  packages/sales-api-service/src/server/routes/renewals.js
  packages/sales-api-service/src/services/renewals/__tests__/renewals.service.spec.js
  packages/sales-api-service/src/services/renewals/renewals.service.js
Labels: enhancement

#1976 Update cookies banner for new analytics
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/layout/layout.njk
Labels: enhancement

#1982 remove full stop
  packages/business-rules-lib/package-lock.json
  packages/connectors-lib/package-lock.json
  packages/dynamics-lib/package-lock.json
  packages/fulfilment-job/package-lock.json
  packages/gafl-webapp-service/package-lock.json
  packages/gafl-webapp-service/src/locales/cy.json
  packages/payment-mop-up-job/package-lock.json
  packages/pocl-job/package-lock.json
  packages/recurring-payments-job/package-lock.json
  packages/sales-api-service/package-lock.json
  packages/sqs-receiver-service/package-lock.json
Labels: enhancement

#1966 Incorrect details on Welsh payment screen
  packages/gafl-webapp-service/src/processors/__tests__/licence-type-display.spec.js
  packages/gafl-webapp-service/src/processors/licence-type-display.js
  packages/gafl-webapp-service/src/services/payment/__test__/govuk-pay-service.spec.js
Labels: bug

#1986 Update privacy policy
  packages/gafl-webapp-service/src/locales/cy.json
  packages/gafl-webapp-service/src/locales/en.json
  packages/gafl-webapp-service/src/pages/guidance/privacy-policy.njk
Labels: enhancement

#1987 Correcting spelling error in accessibility statement
  packages/gafl-webapp-service/src/locales/en.json
Labels: bug
